

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

from app.models.schemas import Scene, StoryboardResponse

router = APIRouter()


@router.post("/export-html", response_class=HTMLResponse, summary="Export storyboard as portable HTML")
async def export_html(storyboard: StoryboardResponse) -> HTMLResponse:
    cards_html = "\n".join(_render_card(scene) for scene in storyboard.scenes)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Storyboard Export — {storyboard.style}</title>
  <style>
    *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      background: #0d0d14;
      color: #e0e0f0;
      font-family: 'Segoe UI', system-ui, sans-serif;
      padding: 2rem;
    }}
    header {{
      text-align: center;
      margin-bottom: 2.5rem;
    }}
    header h1 {{
      font-size: 2rem;
      background: linear-gradient(135deg, #818cf8, #c084fc);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
    }}
    header p {{ color: #6b7280; margin-top: .5rem; font-size: .9rem; }}
    .grid {{
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
      gap: 1.5rem;
    }}
    .card {{
      background: #16162a;
      border: 1px solid #2d2d4e;
      border-radius: 12px;
      overflow: hidden;
    }}
    .card img, .card .placeholder {{
      width: 100%;
      aspect-ratio: 1;
      object-fit: cover;
      display: block;
      background: #1a1a2e;
    }}
    .card-body {{ padding: 1rem; }}
    .beat-index {{
      font-size: .7rem;
      font-weight: 700;
      letter-spacing: .1em;
      color: #818cf8;
      text-transform: uppercase;
      margin-bottom: .4rem;
    }}
    .caption {{ font-size: .85rem; line-height: 1.55; color: #c0c0d8; }}
    footer {{
      text-align: center;
      margin-top: 3rem;
      color: #3d3d5c;
      font-size: .75rem;
    }}
  </style>
</head>
<body>
  <header>
    <h1>🎬 Pitch Visualizer</h1>
    <p>Style: <strong>{storyboard.style}</strong> &nbsp;·&nbsp;
       {storyboard.total_beats} scenes &nbsp;·&nbsp;
       Provider: {storyboard.provider_chain[-1]}</p>
  </header>
  <main class="grid">
{cards_html}
  </main>
  <footer>Generated by Pitch Visualizer · Self-contained export</footer>
</body>
</html>"""

    return HTMLResponse(
        content=html,
        headers={"Content-Disposition": 'attachment; filename="storyboard.html"'},
    )


def _render_card(scene: Scene) -> str:
    if scene.image_format == "base64" and scene.image_data:
        img_tag = (
            f'<img src="data:image/png;base64,{scene.image_data}" '
            f'alt="Scene {scene.beat_index + 1}" />'
        )
    elif scene.image_format == "placeholder" and scene.image_data:
        img_tag = (
            f'<img src="data:image/svg+xml;base64,{scene.image_data}" '
            f'alt="Placeholder scene {scene.beat_index + 1}" />'
        )
    elif scene.image_format == "url" and scene.image_data:
        img_tag = (
            f'<img src="{scene.image_data}" '
            f'alt="Scene {scene.beat_index + 1}" />'
        )
    else:
        img_tag = '<div class="placeholder"></div>'

    return f"""    <div class="card">
      {img_tag}
      <div class="card-body">
        <div class="beat-index">Scene {scene.beat_index + 1}</div>
        <p class="caption">{scene.original_text}</p>
      </div>
    </div>"""
